name: UHC
version: 5.8
authors:
  - StarSnake
  - Nicoseal
main: com.nakeseal.uhc.UHC
api-version: 1.14
commands:
  prepare:
    description: Prepare the game zone.
    usage: /prepare <map-size>
  team:
    description: Commands for team management.
    usage: /team [list|join] [|team-name]
  tc:
    description: Team chat.
    usage: /tc <message>
  inv:
    description: Open a player inventory.
    usage: /inv <player>
  report:
    description: Report a player.
    usage: /report <player-to-report> <message>
